# Generated by Django 5.2.14 on 2026-06-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originality_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('methodology_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scientific_value_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField()),
                ('decision', models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('MODIFY', 'Modify')], max_length=20)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='research.researchpaper')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
