# Generated by Django 5.2.14 on 2026-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_mode', models.CharField(choices=[('full_open', 'وصول مفتوح بالكامل (جميع الأبحاث مجانية للجميع)'), ('full_closed', 'وصول مغلق بالكامل (اشتراك إجباري للـ PDF لجميع الأبحاث)'), ('hybrid', 'نموذج هجين (الوصول مغلق، باستثناء الأبحاث التي دفع مؤلفها رسوم النشر الحر)'), ('abstract_only', 'عرض المستخلص فقط (حجب الـ PDF عن الجميع باستثناء الإدارة والكاتب)')], default='full_open', max_length=20, verbose_name='نمط الوصول العام للمجلة')),
            ],
            options={
                'verbose_name': 'إعدادات الوصول للمجلة',
                'verbose_name_plural': 'إعدادات الوصول للمجلة',
                'db_table': 'JournalConfiguration',
            },
        ),
    ]
