from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.core.management.base import BaseCommand, CommandError

from configuration.models import JournalConfiguration
from research.models import ResearchPaper
from tests_common.files import make_valid_pdf_bytes

User = get_user_model()

LOADTEST_PASSWORD = 'LoadTest123!'

ROLE_COUNTS = [
    ('author', 5),
    ('reviewer', 3),
    ('editor', 2),
    ('assistant_editor', 2),
    ('admin', 1),
    ('reader', 3),
]

STATUS_COUNTS = [
    (ResearchPaper.Status.PUBLISHED, 15),
    (ResearchPaper.Status.PENDING, 5),
    (ResearchPaper.Status.SUBMITTED, 5),
    (ResearchPaper.Status.EDITOR_REVIEW, 3),
    (ResearchPaper.Status.COMMITTEE_REVIEW, 3),
    (ResearchPaper.Status.REVISION_REQUIRED, 2),
    (ResearchPaper.Status.REJECTED, 2),
]


class Command(BaseCommand):
    help = (
        "Seed fixed-credential users and a spread of papers for Locust load testing. "
        "DESTRUCTIVE-ADJACENT: creates accounts with a KNOWN, SHARED password — never run "
        "this against a real production database. Intended for a disposable local/CI "
        "database copy only (see loadtest/README.md)."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            '--yes', action='store_true',
            help="Required acknowledgement that this is a disposable database, not production.",
        )

    def handle(self, *args, **options):
        if not options['yes']:
            raise CommandError(
                "Refusing to run without --yes. This command creates users with a KNOWN, "
                "SHARED password (LoadTest123!) — only run it against a disposable database "
                "copy, never against real production data. Re-run with --yes to confirm."
            )

        JournalConfiguration.objects.get_or_create(pk=1, defaults={'system_mode': 'full_open'})

        users_by_role = {role: [] for role, _ in ROLE_COUNTS}
        for role, count in ROLE_COUNTS:
            for i in range(1, count + 1):
                email = f'loadtest_{role}{i}@example.com'
                user, _ = User.objects.get_or_create(
                    email=email,
                    defaults={
                        'full_name': f'Loadtest {role.replace("_", " ").title()} {i}',
                        'role': role,
                        'specialization': 'computer_science',
                        'email_verified': True,
                        'is_staff': role == 'admin',
                        'is_superuser': role == 'admin',
                    },
                )
                user.set_password(LOADTEST_PASSWORD)
                user.save(update_fields=['password'])
                users_by_role[role].append(user)

        authors = users_by_role['author']
        paper_count = 0
        for status_value, count in STATUS_COUNTS:
            for i in range(count):
                author = authors[i % len(authors)]
                title = f'Loadtest Paper [{status_value}] #{i + 1}'
                if ResearchPaper.objects.filter(title=title, author=author).exists():
                    continue
                paper = ResearchPaper.objects.create(
                    title=title,
                    abstract='Seed data generated by seed_loadtest_data for Locust runs.',
                    author=author,
                    specialization='computer_science',
                    status=status_value,
                )
                paper.pdf_file.save(f'loadtest_paper_{paper.id}.pdf', ContentFile(make_valid_pdf_bytes(3)), save=True)
                paper_count += 1

        total_users = sum(len(v) for v in users_by_role.values())
        self.stdout.write(self.style.SUCCESS(
            f"Seeded {total_users} user(s) (password: {LOADTEST_PASSWORD} for all) and "
            f"{paper_count} new paper(s). Journal configuration set to full_open."
        ))
