# Generated by Django 5.1.1 on 2026-05-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieeecheckreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ieeecheckreport',
            name='pdf_file',
            field=models.FileField(upload_to='ieee_documents/%Y/%m/', verbose_name='ملف البحث (PDF/DOCX)'),
        ),
    ]
