# Generated by Django 6.0.5 on 2026-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0002_alter_ieeecheckreport_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieeecheckreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
