# Generated by Django 6.0.5 on 2026-06-11 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0004_alter_ieeecheckreport_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimEvidenceGraphReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(max_length=500, upload_to='claim_evidence_documents/%Y/%m/', verbose_name='ملف البحث (PDF/DOCX)')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('paper_title', models.CharField(blank=True, max_length=500, verbose_name='عنوان الورقة')),
                ('detected_language', models.CharField(blank=True, max_length=10, verbose_name='اللغة المكتشفة')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('processing', 'جارٍ التحليل'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=12, verbose_name='الحالة')),
                ('graph_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الرسم البياني')),
                ('claims_count', models.PositiveIntegerField(default=0, verbose_name='عدد الادعاءات')),
                ('evidence_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأدلة')),
                ('neutral_count', models.PositiveIntegerField(default=0, verbose_name='عدد الجمل المحايدة')),
                ('edges_count', models.PositiveIntegerField(default=0, verbose_name='عدد الروابط')),
                ('similarity_threshold', models.FloatField(default=0.5, verbose_name='عتبة التشابه')),
                ('source_excerpt', models.TextField(blank=True, verbose_name='مقتطف من النص المصدر')),
                ('summary', models.TextField(blank=True, verbose_name='الملخص')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processing_time_seconds', models.FloatField(blank=True, null=True, verbose_name='وقت المعالجة (ثانية)')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_evidence_reports', to=settings.AUTH_USER_MODEL, verbose_name='طُلب من قِبل')),
            ],
            options={
                'verbose_name': 'تقرير رسم الادعاء-الدليل',
                'verbose_name_plural': 'تقارير رسم الادعاء-الدليل',
                'ordering': ['-created_at'],
            },
        ),
    ]
