# Generated by Django 6.0.5 on 2026-06-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0005_claimevidencegraphreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimevidencegraphreport',
            name='top_claims_count',
            field=models.PositiveIntegerField(default=10, verbose_name='عدد أهم الادعاءات'),
        ),
    ]
