# Generated by Django 5.2.14 on 2026-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
