# Generated by Django 6.0.5 on 2026-08-02 19:13

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[accounts.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
