# Generated by Django 5.2.14 on 2026-07-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.DateTimeField(max_length=32, null=True),
        ),
    ]
