# Generated by Django 6.0.5 on 2026-07-01 17:29

from django.db import migrations, models


def rename_role(apps, _schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='reviewer_assistant').update(role='assistant_editor')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_specialization'),
    ]

    operations = [
        migrations.RunPython(rename_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('editor', 'محرر'), ('reviewer', 'محكم'), ('assistant_editor', 'مساعد المحرر'), ('author', 'باحث'), ('reader', 'قارئ')], default='author', max_length=20),
        ),
    ]
