# Generated by Django 5.2.14 on 2026-07-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_specialization'),
        ('accounts', '0004_rename_reviewer_assistant_to_assistant_editor'),
    ]

    operations = [
    ]
