# Generated by Django 6.0.5 on 2026-07-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260702_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
