# Generated by Django 5.2.14 on 2026-06-23 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_service', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_format_compliant', models.BooleanField(default=True)),
                ('is_complete', models.BooleanField(default=True)),
                ('policy_notes', models.TextField(blank=True, default='')),
                ('recommended_decision', models.CharField(blank=True, choices=[('SEND_TO_COMMITTEE', 'Send To Committee'), ('REVISION_REQUIRED', 'Revision Required'), ('REJECT', 'Reject')], max_length=30)),
                ('notes', models.TextField()),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant', models.ForeignKey(limit_choices_to={'role': 'reviewer_assistant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ieee_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reviews', to='ai_service.ieeecheckreport')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_reviews', to='research.researchpaper')),
                ('suggested_reviewers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'reviewer'}, related_name='suggested_in_assistant_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
