# Generated by Django 5.2.14 on 2026-06-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('assistant', models.ForeignKey(limit_choices_to={'role': 'reviewer_assistant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_review', to='research.researchpaper')),
            ],
        ),
    ]
