# Generated by Django 6.0.5 on 2026-06-11 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0004_alter_ieeecheckreport_pdf_file'),
        ('assistantReview', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantreview',
            options={'ordering': ['-reviewed_at']},
        ),
        migrations.AddField(
            model_name='assistantreview',
            name='ieee_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_reviews', to='ai_service.ieeecheckreport'),
        ),
        migrations.AddField(
            model_name='assistantreview',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantreview',
            name='is_format_compliant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantreview',
            name='policy_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assistantreview',
            name='recommended_decision',
            field=models.CharField(blank=True, choices=[('SEND_TO_COMMITTEE', 'Send To Committee'), ('REVISION_REQUIRED', 'Revision Required'), ('REJECT', 'Reject')], max_length=30),
        ),
        migrations.AddField(
            model_name='assistantreview',
            name='suggested_reviewers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'reviewer'}, related_name='suggested_in_assistant_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assistantreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assistantreview',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_reviews', to='research.researchpaper'),
        ),
    ]
