# Generated by Django 5.2.14 on 2026-06-23 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد التشكيل'), ('approved', 'تمت الموافقة على اللجنة'), ('rejected', 'مرفوضة'), ('revision', 'مطلوب تعديلات')], default='pending', max_length=20)),
                ('blinding_type', models.CharField(choices=[('open', 'مفتوح'), ('single_blind', 'تعمية أحادية'), ('double_blind', 'تعمية ثنائية')], default='single_blind', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_committees', to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='research.researchpaper')),
            ],
            options={
                'db_table': 'Committee',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'أساسي'), ('substitute', 'بديل')], max_length=15)),
                ('response', models.CharField(choices=[('pending', 'بانتظار الرد'), ('accepted', 'وافق'), ('declined', 'اعتذر')], default='pending', max_length=15)),
                ('paper_decision', models.CharField(choices=[('pending', 'قيد الدراسة'), ('accept_paper', 'قبول الورقة'), ('reject_paper', 'رفض الورقة'), ('modify_paper', 'طلب تعديلات')], default='pending', max_length=15)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_substitute', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(blank=True, default=None, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_assigned_members', to='committees.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CommitteeMember',
                'unique_together': {('committee', 'user')},
            },
        ),
    ]
