# Generated by Django 6.0.5 on 2026-06-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد التشكيل'), ('approved', 'تمت الموافقة على اللجنة'), ('accepted', 'تمت الموافقة على الورقة'), ('rejected', 'مرفوضة'), ('revision', 'مطلوب تعديلات'), ('expired', 'منتهية الصلاحية')], default='pending', max_length=20),
        ),
    ]
