<<<<<<< HEAD
# Generated by Django 5.2.15 on 2026-07-03 17:43
=======
# Generated by Django 5.2.14 on 2026-06-24 20:35
>>>>>>> 8009729a235f7b93b8bdf2dd63e85d842a3aade5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_similarity_score', models.FloatField()),
                ('ai_keywords', models.JSONField(blank=True, default=list)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlagiarismSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('source_title', models.CharField(max_length=255)),
                ('match_percentage', models.FloatField()),
                ('matched_text_snippet', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='research.plagiarismreport')),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 8009729a235f7b93b8bdf2dd63e85d842a3aade5
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='papers_pdf/')),
                ('is_paid_open_access', models.BooleanField(default=False)),
<<<<<<< HEAD
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('checking_plagiarism', 'Checking Plagiarism'), ('editor_review', 'Editor Review'), ('revision_required', 'Revision Required'), ('committee_review', 'Committee Review'), ('accepted', 'Accepted'), ('published', 'Published'), ('rejected', 'Rejected'), ('plagiarism_failed', 'Plagiarism Failed')], default='pending', max_length=25)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.CharField(max_length=32, null=True)),
                ('assistant_editor_report', models.TextField(blank=True, null=True)),
                ('is_reviewed_by_assistant', models.BooleanField(default=False)),
                ('review_blindness_type', models.CharField(choices=[('single_blind', 'Single Blind'), ('double_blind', 'Double Blind'), ('open_review', 'Open Review')], default='double_blind', max_length=20)),
=======
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
>>>>>>> 8009729a235f7b93b8bdf2dd63e85d842a3aade5
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ResearchPaper',
            },
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='plagiarismreport',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='research.researchpaper'),
        ),
=======
>>>>>>> 8009729a235f7b93b8bdf2dd63e85d842a3aade5
    ]
