# Generated by Django 5.2.14 on 2026-06-28 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('checking_plagiarism', 'Checking Plagiarism'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('plagiarism_failed', 'Plagiarism Failed')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_similarity_score', models.FloatField()),
                ('ai_keywords', models.JSONField(blank=True, default=list)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='research.researchpaper')),
            ],
        ),
        migrations.CreateModel(
            name='PlagiarismSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('source_title', models.CharField(max_length=255)),
                ('match_percentage', models.FloatField()),
                ('matched_text_snippet', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='research.plagiarismreport')),
            ],
        ),
    ]
