# Generated by Django 5.2.14 on 2026-06-13 18:33

import research.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='paper_file',
            field=models.FileField(upload_to='papers/', validators=[research.validators.validate_file_size]),
        ),
    ]
