# Generated by Django 5.2.14 on 2026-06-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_researchpaper_status_plagiarismreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='assistant_editor_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='is_reviewed_by_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='review_blindness_type',
            field=models.CharField(choices=[('single_blind', 'Single Blind'), ('double_blind', 'Double Blind'), ('open_review', 'Open Review')], default='double_blind', max_length=20),
        ),
    ]
