# Generated by Django 5.2.14 on 2026-07-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchpaper_assistant_editor_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='specialization',
            field=models.DateTimeField(max_length=32, null=True),
        ),
    ]
