# Generated by Django 6.0.5 on 2026-07-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchpaper_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('checking_plagiarism', 'Checking Plagiarism'), ('editor_review', 'Editor Review'), ('revision_required', 'Revision Required'), ('committee_review', 'Committee Review'), ('accepted', 'Accepted'), ('published', 'Published'), ('rejected', 'Rejected'), ('plagiarism_failed', 'Plagiarism Failed')], default='pending', max_length=25),
        ),
    ]
