# Generated by Django 5.2.14 on 2026-07-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchpaper_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='specialization',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
