# Generated by Django 5.2.14 on 2026-07-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_researchpaper_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('checking_plagiarism', 'Checking Plagiarism'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('plagiarism_failed', 'Plagiarism Failed'), ('editor_review', 'Editor Review'), ('committee_review', 'Committee Review'), ('accepted', 'Accepted'), ('published', 'Published')], default='pending', max_length=25),
        ),
    ]
