# Generated by Django 5.2.14 on 2026-07-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_researchpaper_status'),
        ('research', '0006_alter_researchpaper_status'),
    ]

    operations = [
    ]
