# Generated by Django 6.0.5 on 2026-07-03 16:32

import research.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_merge_20260702_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='papers_pdf/', validators=[research.validators.validate_file_size]),
        ),
    ]
