# Generated by Django 5.2.15 on 2026-07-25 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_pdf_extension_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismreport',
            name='external_similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='internal_similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped')], default='completed', max_length=15),
        ),
        migrations.AddField(
            model_name='plagiarismsource',
            name='matched_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarism_matches_as_source', to='research.researchpaper'),
        ),
        migrations.AddField(
            model_name='plagiarismsource',
            name='source_type',
            field=models.CharField(choices=[('internal', 'Internal (platform corpus)'), ('external', 'External (web/academic search)')], default='external', max_length=10),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='total_similarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='plagiarismsource',
            name='source_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='plagiarismsource',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='PaperChunkEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding_vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_embeddings', to='research.researchpaper')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
    ]
