# Generated by Django 5.2.15 on 2026-07-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_plagiarism_rebuild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plagiarismsource',
            name='matched_text_snippet',
        ),
        migrations.AddField(
            model_name='plagiarismsource',
            name='own_text_snippet',
            field=models.TextField(default='', help_text='النص من البحث المُقدَّم الذي طابق المصدر'),
        ),
        migrations.AddField(
            model_name='plagiarismsource',
            name='source_text_snippet',
            field=models.TextField(blank=True, default='', help_text='النص المقابل من المصدر (بحث آخر داخلي، أو ملخص/نص خارجي)'),
        ),
    ]
