# Generated by Django 5.2.15 on 2026-07-27 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_plagiarism_source_text_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='research.researchpaper')),
            ],
        ),
    ]
