# Generated by Django 5.2.15 on 2026-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_paperembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperchunkembedding',
            name='base_embedding_vector',
            field=models.JSONField(blank=True, help_text='متجه النموذج الأساس (للمقارنات العابرة للغات، عربي↔غير عربي)', null=True),
        ),
        migrations.AddField(
            model_name='paperchunkembedding',
            name='detected_language',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='paperchunkembedding',
            name='embedding_vector',
            field=models.JSONField(help_text='متجه النموذج المُضبَط دقيقاً (الأفضل للعربي-عربي)'),
        ),
    ]
