# Generated by Django 5.2.15 on 2026-07-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_paperchunkembedding_base_embedding_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismreport',
            name='requires_human_review',
            field=models.BooleanField(default=False, help_text="صحيح إذا وُجد تشابه بمستوى 'مشتبه به' فقط (دون أي تطابق مؤكَّد) — يحتاج مراجعة بشرية قبل القرار"),
        ),
        migrations.AddField(
            model_name='plagiarismsource',
            name='confidence_level',
            field=models.CharField(choices=[('confirmed', 'Confirmed match'), ('suspected', 'Suspected paraphrase — needs human review')], default='confirmed', help_text='مؤكَّد (فوق حد الكشف الأساسي) أو مشتبه به (تشابه دلالي متوسط قد يكون إعادة صياغة، يحتاج مراجعة بشرية)', max_length=10),
        ),
    ]
