# Generated by Django 5.2.15 on 2026-07-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_plagiarismreport_requires_human_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperchunkembedding',
            name='is_citation',
            field=models.BooleanField(default=False, help_text='اقتباس مُصرَّح به (علامات تنصيص + إشارة استشهاد) — يُستبعَد من مقارنة الانتحال الداخلية'),
        ),
    ]
