# Generated by Django 6.0.5 on 2026-08-02 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_plagiarismreport_requires_human_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المعالجة'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=12)),
                ('overall_score', models.FloatField(default=0.0)),
                ('sub_scores', models.JSONField(blank=True, default=dict)),
                ('breakdown', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_quality_report', to='research.researchpaper')),
            ],
            options={
                'db_table': 'MetadataQualityReport',
            },
        ),
    ]
