# Generated by Django 6.0.5 on 2026-08-02 19:13

import django.core.validators
import research.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0017_paperdownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='papers_pdf/', validators=[research.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), research.validators.validate_pdf_content]),
        ),
    ]
