# Generated by Django 5.2.15 on 2026-08-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_paperchunkembedding_is_citation'),
        ('research', '0018_alter_researchpaper_pdf_file'),
    ]

    operations = [
    ]
