# Generated by Django 5.2.15 on 2026-08-12 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0019_merge_20260803_0451'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='assigned_assistant_editor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'assistant_editor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assistant_papers', to=settings.AUTH_USER_MODEL),
        ),
    ]
