# Generated by Django 5.2.14 on 2026-06-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_service', '0004_alter_ieeecheckreport_pdf_file'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('decision', models.CharField(choices=[('SEND_TO_COMMITTEE', 'Send To Committee'), ('REVISION_REQUIRED', 'Revision Required'), ('REJECT', 'Reject')], max_length=30)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(limit_choices_to={'role': 'editor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ieee_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_service.ieeecheckreport')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_review', to='research.researchpaper')),
            ],
        ),
    ]
