# Generated by Django 6.0.5 on 2026-06-11 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_service', '0004_alter_ieeecheckreport_pdf_file'),
        ('editorReview', '0001_initial'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorreview',
            options={'ordering': ['-reviewed_at']},
        ),
        migrations.AddField(
            model_name='editorreview',
            name='citation_check_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorreview',
            name='language_review_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorreview',
            name='publisher_permission_obtained',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorreview',
            name='stage',
            field=models.CharField(choices=[('INITIAL', 'مراجعة أولية'), ('FINAL', 'مراجعة نهائية')], default='INITIAL', max_length=10),
        ),
        migrations.AddField(
            model_name='editorreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='editorreview',
            name='decision',
            field=models.CharField(choices=[('SEND_TO_COMMITTEE', 'Send To Committee'), ('REVISION_REQUIRED', 'Revision Required'), ('REJECT', 'Reject'), ('ACCEPT', 'Accept')], max_length=30),
        ),
        migrations.AlterField(
            model_name='editorreview',
            name='ieee_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_service.ieeecheckreport'),
        ),
        migrations.AlterField(
            model_name='editorreview',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_reviews', to='research.researchpaper'),
        ),
    ]
