# Generated by Django 6.0.5 on 2026-08-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('paper_submitted', 'تقديم بحث جديد'), ('paper_status_changed', 'تغيّر حالة البحث'), ('paper_published', 'نشر البحث'), ('assistant_review_received', 'مراجعة مساعد المحرر'), ('editor_review_received', 'مراجعة المحرر'), ('committee_review_received', 'قرار لجنة التحكيم'), ('committee_deadline_approaching', 'اقتراب موعد اللجنة'), ('committee_deadline_expired', 'انتهاء مهلة اللجنة'), ('editor_assigned', 'تعيين محرر'), ('reviewer_assigned_to_committee', 'تعيين محكم في لجنة'), ('role_changed', 'تغيّر الصلاحية'), ('system_announcement', 'إعلان من الإدارة'), ('discussion_mention', 'إشارة في نقاش'), ('issue_published', 'نشر عدد جديد')], db_index=True, max_length=40)),
                ('level', models.CharField(choices=[('info', 'معلومة'), ('success', 'نجاح'), ('warning', 'تنبيه'), ('critical', 'حرج')], default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, default='', max_length=255)),
                ('group_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'بريد إلكتروني'), ('push', 'إشعار جوال')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'قيد الإرسال'), ('sent', 'تم الإرسال'), ('failed', 'فشل مؤقت'), ('retrying', 'إعادة محاولة'), ('given_up', 'تم التخلي بعد استنفاد المحاولات')], db_index=True, default='pending', max_length=10)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'NotificationDelivery',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('paper_submitted', 'تقديم بحث جديد'), ('paper_status_changed', 'تغيّر حالة البحث'), ('paper_published', 'نشر البحث'), ('assistant_review_received', 'مراجعة مساعد المحرر'), ('editor_review_received', 'مراجعة المحرر'), ('committee_review_received', 'قرار لجنة التحكيم'), ('committee_deadline_approaching', 'اقتراب موعد اللجنة'), ('committee_deadline_expired', 'انتهاء مهلة اللجنة'), ('editor_assigned', 'تعيين محرر'), ('reviewer_assigned_to_committee', 'تعيين محكم في لجنة'), ('role_changed', 'تغيّر الصلاحية'), ('system_announcement', 'إعلان من الإدارة'), ('discussion_mention', 'إشارة في نقاش'), ('issue_published', 'نشر عدد جديد')], db_index=True, max_length=40)),
                ('channel', models.CharField(choices=[('in_app', 'داخل التطبيق'), ('email', 'بريد إلكتروني'), ('push', 'إشعار جوال')], max_length=10)),
                ('language', models.CharField(default='ar', max_length=5)),
                ('subject_template', models.CharField(blank=True, default='', max_length=255)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'NotificationTemplate',
                'unique_together': {('notification_type', 'channel', 'language')},
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('paper_submitted', 'تقديم بحث جديد'), ('paper_status_changed', 'تغيّر حالة البحث'), ('paper_published', 'نشر البحث'), ('assistant_review_received', 'مراجعة مساعد المحرر'), ('editor_review_received', 'مراجعة المحرر'), ('committee_review_received', 'قرار لجنة التحكيم'), ('committee_deadline_approaching', 'اقتراب موعد اللجنة'), ('committee_deadline_expired', 'انتهاء مهلة اللجنة'), ('editor_assigned', 'تعيين محرر'), ('reviewer_assigned_to_committee', 'تعيين محكم في لجنة'), ('role_changed', 'تغيّر الصلاحية'), ('system_announcement', 'إعلان من الإدارة'), ('discussion_mention', 'إشارة في نقاش'), ('issue_published', 'نشر عدد جديد')], max_length=40)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserNotificationPreference',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DeviceToken',
                'indexes': [models.Index(fields=['user', 'is_active'], name='devicetoken_user_active_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recipient_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notif_recipient_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group_key'], name='notif_group_key_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='notif_target_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'channel'], name='notifdlv_status_channel_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationpreference',
            unique_together={('user', 'notification_type')},
        ),
    ]
