# Generated by Django 6.0.5 on 2026-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_notification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='rendered_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='rendered_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
