# Generated by Django 6.0.5 on 2026-08-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_seed_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='device_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.devicetoken'),
        ),
    ]
