# Generated by Django 5.2.15 on 2026-08-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_seed_push_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('paper_submitted', 'تقديم بحث جديد'), ('paper_status_changed', 'تغيّر حالة البحث'), ('paper_published', 'نشر البحث'), ('assistant_review_received', 'مراجعة مساعد المحرر'), ('editor_review_received', 'مراجعة المحرر'), ('committee_review_received', 'قرار لجنة التحكيم'), ('committee_deadline_approaching', 'اقتراب موعد اللجنة'), ('committee_deadline_expired', 'انتهاء مهلة اللجنة'), ('editor_assigned', 'تعيين محرر'), ('assistant_editor_assigned', 'تعيين مساعد محرر'), ('reviewer_assigned_to_committee', 'تعيين محكم في لجنة'), ('role_changed', 'تغيّر الصلاحية'), ('system_announcement', 'إعلان من الإدارة'), ('discussion_mention', 'إشارة في نقاش'), ('issue_published', 'نشر عدد جديد')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('paper_submitted', 'تقديم بحث جديد'), ('paper_status_changed', 'تغيّر حالة البحث'), ('paper_published', 'نشر البحث'), ('assistant_review_received', 'مراجعة مساعد المحرر'), ('editor_review_received', 'مراجعة المحرر'), ('committee_review_received', 'قرار لجنة التحكيم'), ('committee_deadline_approaching', 'اقتراب موعد اللجنة'), ('committee_deadline_expired', 'انتهاء مهلة اللجنة'), ('editor_assigned', 'تعيين محرر'), ('assistant_editor_assigned', 'تعيين مساعد محرر'), ('reviewer_assigned_to_committee', 'تعيين محكم في لجنة'), ('role_changed', 'تغيّر الصلاحية'), ('system_announcement', 'إعلان من الإدارة'), ('discussion_mention', 'إشارة في نقاش'), ('issue_published', 'نشر عدد جديد')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='usernotificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('paper_submitted', 'تقديم بحث جديد'), ('paper_status_changed', 'تغيّر حالة البحث'), ('paper_published', 'نشر البحث'), ('assistant_review_received', 'مراجعة مساعد المحرر'), ('editor_review_received', 'مراجعة المحرر'), ('committee_review_received', 'قرار لجنة التحكيم'), ('committee_deadline_approaching', 'اقتراب موعد اللجنة'), ('committee_deadline_expired', 'انتهاء مهلة اللجنة'), ('editor_assigned', 'تعيين محرر'), ('assistant_editor_assigned', 'تعيين مساعد محرر'), ('reviewer_assigned_to_committee', 'تعيين محكم في لجنة'), ('role_changed', 'تغيّر الصلاحية'), ('system_announcement', 'إعلان من الإدارة'), ('discussion_mention', 'إشارة في نقاش'), ('issue_published', 'نشر عدد جديد')], max_length=40),
        ),
    ]
